
  name: Test-Workflow
  on:
    push:
      paths-ignore:
          - README.md
    pull_request:
      types:
        - opened
    workflow_dispatch:
  jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name : getCode
            uses: actions/checkout@v3
          - name : Isntall node
            uses : actions/setup-node@v3
            with :
              node-version: 18
          - name : Install dependencies
            run : npm ci
          - name : Run Tests
            run : npm test
          - name: Output Contents
            run : ls -lh            
          - uses: actions/upload-artifact@v3
            with:
              name: dist-files
              path: | 
                dist
                package.json
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: dist-files
        - name: Output Contents
          run : ls -lh
        - name: Deploy
          run : echo "Deploying....."
        