
  name: Test-Workflow
  on:
    pull_request:
      types:
        - opened
    workflow_dispatch:
    # push:
    #     paths-ignore:
    #         - README.md

  jobs:
    test:
        runs-on: ubuntu-latest
        steps:
          - name : getCode
            uses: actions/checkout@v3
          - name : Isntall node
            uses : actions/setup-node@v3
            with :
              node-version: 18
          - name : Install dependencies
            run : npm ci
          - name : Run Tests
            run : npm test
          - uses: actions/upload-artifact@v3
            with:
              name: dist-files
              path: dist  
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v3
          with:
            name: dist-files
        - name: Output Contents
          run : ls -lHa
        - name: Deploy
          run : echo "Deploying....."
        