
  name: Test-Workflow
  on: 
    push:
        paths-ignore:
            - README.md

  jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
          - name : getCode
            uses: actions/checkout@v3
          - name : Print
            run: echo '${{ toJSON(github) }}'
          - name : Print github variables
            run : echo ${{ github.event_name }}
        
        